---
title: "Shrimp Analysis (FISH 513)"
author: "Connor Quiroz"
date: "2025-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# For reading in .parquet files
library(arrow)

# Data processing package
library(tidyverse)
library(patchwork)

# Map creation
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)

# For Packages for fishbase
remotes::install_github("cboettig/duckdbfs", force = TRUE)
remotes::install_github("ropensci/rfishbase")
library(duckdbfs)
library(rfishbase)

# Load in packages needed for ARTIS
library(devtools)
library(tidytext)
devtools::install_github("davidsjoberg/ggsankey")
library(ggsankey)
devtools::install_github("Seafood-Globalization-Lab/exploreARTIS@v1.0.0", dependencies = TRUE)
library(exploreARTIS)

library(rgbif)

# Convert countries to iso3c
library(countrycode)

# for parallel processing
library(parallel)
```

```{r create function}
# Ocean polygon
ocean <- st_polygon(list(cbind(c(seq(-180, 179, len = 100), rep(180, 100), 
                        seq(179, -180, len = 100), rep(-180, 100)),
                      c(rep(-90, 100), seq(-89, 89, len = 100),
                        rep(90, 100), seq(89, -90, len = 100))))) |>
  st_sfc(crs = "WGS84") |>
  st_as_sf()

# Make map creation simpler
create_map <- function(data, fill = "num_species") {
  world_map <- ne_countries(scale = "medium", returnclass = "sf")

world_map <- world_map %>%
  left_join(data, by = c("iso_a3" = "country"))
  
  world_map %>%
ggplot() +
  geom_sf(data = ocean, fill = "#8080ff80") +
  geom_sf(aes(fill = !!sym(fill)), color = "black") + 
  scale_fill_viridis_c(option = "plasma") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  coord_sf(crs = "+proj=robin")
}


# FUNCTION DEFINITION: Obtain gbif abundance data
  gbif_abundance <- function(scientific_name = "") {
  # Create an empty data frame to store date and count
    
  gbif_data <- data.frame()
  # Loop over each year from 1920 to 2024

    
  for (j in countries) {
    result <- data.frame(
      date = make_date(2024:2024, 1, 1),
      country = rep(j, each = length(2024:2024)),
      count = NA
    )
    for (i in 2024:2024) {
      # Fetch count of occurrences for the given scientific name and year
      value <- occ_count(scientificName = scientific_name,
                         year = i,
                         country = j)
      
      # Assign the count value to the respective row in the result data frame
      result$count[which(result$date == make_date(i, 1, 1) &
                           result$country == j)] <- value
      print(c(i,j))
    }
    gbif_data <- bind_rows(gbif_data, result)
    
  }
  
  return(gbif_data)
  }
  

# FUNCTION DEFINITION: Obtain gbif abundance data
gbif_abundance <- function(scientific_name = "", countries) {
  # Create an empty data frame to store the data
  gbif_data <- data.frame()
  
  # Create an empty list to collect debug information
  debug_info <- list()
  
  # Loop over each country in the countries list
  for (j in countries) {
    result <- data.frame(
      date = make_date(1920:2024, 1, 1),
      country = rep(j, each = length(1920:2024)),
      count = NA
    )
    
    # Loop over each year from 1920 to 2024
    for (i in 1920:2024) {
      # Fetch count of occurrences for the given scientific name, year, and country
      value <- tryCatch({
        occ_count(scientificName = scientific_name, year = i, country = j)
      }, error = function(e) {
        debug_info[[length(debug_info) + 1]] <- paste("Error fetching data for", scientific_name, "in", j, "for year", i)
        return(NA)  # Return NA if there's an error
      })
      
      # If the API returns a valid count, assign it to the result data frame
      if (!is.null(value)) {
        result$count[which(result$date == make_date(i, 1, 1) & result$country == j)] <- value
      }
      
      # Store debug information (e.g., year, country, occurrences) without printing
      debug_info[[length(debug_info) + 1]] <- paste("Year:", i, "Country:", j, "Occurrences:", value)
    }
    
    # Bind the result data to the main dataframe
    gbif_data <- bind_rows(gbif_data, result)
  }
  
  # After the function finishes, print the debug info
  # You can view the debug info if needed by uncommenting the following line:
  # print(debug_info)
  
  # Return the final GBIF data frame
  return(gbif_data)
}



# FUNCTION DEFINITION: Create time series of previously obtained gbif data
gbif_time_series <- function(data = data,
                             taxa_name = "",
                             group_by_region = TRUE) {
  if (group_by_region == TRUE) {
    plot <- data %>%
      group_by(date, region) %>%
      drop_na() %>%
      summarize(count = sum(count)) %>%
      drop_na() %>%
      ggplot(aes(x = date, y = count, color = region)) +
      geom_line() +
      theme_light() +
      labs(x = "", y = paste0(taxa_name, " count"), color = "Region") +
      scale_color_manual(values = artis_palette(7))
  }
  else {
    plot <- data %>%
      group_by(date) %>%
      drop_na() %>%
      summarize(count = sum(count)) %>%
      ggplot(aes(x = date, y = count)) +
      geom_line() +
      labs(x = " ", y = paste0(taxa_name, " count")) +
      theme_light() +
      geom_smooth(method = "")
  }
  return(plot)
}
```


```{r  Obtain sealifebase data}
if (!file.exists("data/slb_presences_country.parquet")) {
  # Obtain SLB country() data + species codes
  slb_presences_country <- country(server = "sealifebase")
  slb_species_codes <- load_taxa(server = "sealifebase")
  
  # Join SLB country() to species codes
  slb_presences_country <- slb_presences_country %>%
    left_join(slb_species_codes, by = "SpecCode")
  
  if (!file.exists("data/slb_common_names.parquet")) {
    # Get SLB common names
  slb_common_names <- common_names(species_list = slb_species, server = "sealifebase")
  }
  
  # Write files to .parquet
  write_parquet(slb_presences_country, "data/slb_presences_country.parquet")
  write_parquet(slb_common_names, "data/slb_common_names.parquet")
}
```

> Last date obtained: January 7

```{r Read in + analyze sealifebase data}
# Read in sealifebase data
slb <- read_parquet("data/slb_presenceS_country.parquet")
slb <- slb %>% 
  rename(CommonName = "Species") %>%
  mutate(Species = str_split(CommonName, " ")[[1]][1])
slb_common_names <- read_parquet("data/slb_common_names.parquet")

# Read in HDI data
hdi <- read_csv("data/hdi.csv")
hdi <- hdi %>%
  mutate(country = countrycode(country, origin = "country.name", destination = "iso3c")) %>%
  exploreARTIS::add_region("country", region.col.name = "region")

# Reorganize column names 
slb <- slb %>%
  relocate(c("Species", "Genus", "TrueSpecies"), .after = "SpecCode")

# Join scinames to common names
slb <- left_join(slb, slb_common_names[,c(2,4)], by = "SpecCode") %>%
  relocate("ComName", .after = "TrueSpecies")

slb_shrimp <- slb %>%
  filter(str_detect(ComName, regex("shrimp", ignore_case = TRUE)))

# Obtain number of all shrimp species
# Need to manually assign iso3c values
num_all_species_iso3c <- slb_shrimp %>%
  group_by(country) %>%
  distinct(Species) %>%
  summarize(num_species = length(Species)) %>%
  arrange(-num_species) %>%
  mutate(country = countrycode(country, origin = "country.name", destination = "iso3c"))

# Same thing but for genus
num_all_genus_iso3c <- slb_shrimp %>%
  group_by(country) %>%
  distinct(Genus) %>%
  summarize(num_species = length(Genus)) %>%
  arrange(-num_species) %>%
  mutate(country = countrycode(country, origin = "country.name", destination = "iso3c"))

# Obtain number of all commercial shrimp species
num_commercial_species <- slb_shrimp %>%
  filter(Importance %in% c("minor commercial", "highly commercial", "commercial", "subsistence fisheries", "of potential interest") | (!is.na(Aquaculture) & Aquaculture != "never/rarely"), Status != "misidentification")

# Obtain number of all commercial shrimp species
num_commercial_species_iso3c <- num_commercial_species %>%
  group_by(country) %>%
  distinct(Species) %>%
  summarize(num_species = length(Species)) %>%
  arrange(-num_species) %>%
  mutate(country = countrycode(country, origin = "country.name", destination = "iso3c"))

# ... genus
num_commercial_genus_iso3c <- num_commercial_species %>%
  group_by(country) %>%
  distinct(Genus) %>%
  summarize(num_species = length(Genus)) %>%
  arrange(-num_species) %>%
  mutate(country = countrycode(country, origin = "country.name", destination = "iso3c"))

# Obtain number of introduced shrimp species
introduced_species <- slb_shrimp %>%
  filter(Status == "introduced") %>%
  group_by(country) %>%
  distinct(Species) %>%
  summarize(num_species = length(Species)) %>%
  arrange(-num_species) %>%
  mutate(country = countrycode(country, origin = "country.name", destination = "iso3c"))

introduced_genus <- slb_shrimp %>%
  filter(Status == "introduced") %>%
  group_by(country) %>%
  distinct(Genus) %>%
  summarize(num_species = length(Genus)) %>%
  arrange(-num_species) %>%
  mutate(country = countrycode(country, origin = "country.name", destination = "iso3c"))

left_join(introduced_genus, hdi, by = "country") %>%
    filter(!is.na(region)) %>%
  ggplot(aes(x = hdi, y = log(num_species), color = region)) +
  geom_point() +
    scale_color_viridis_d(end = 0.9) + 
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Human Development Index", y = "log(Shrimp Species Count", color = "Region") +
    theme_light()
```

```{r plot data}
(all_species_count_map <- create_map(num_all_species_iso3c) +
  labs(fill = "Shrimp species count"))

(all_genus_count_map <- create_map(num_all_genus_iso3c) +
  labs(fill = "Shrimp genus count"))

(commercial_species_count_map <- create_map(num_commercial_species_iso3c) +
  labs(fill = "Commercial Shrimp Species Count"))

(commercial_genus_count_map <- create_map(num_commercial_genus_iso3c) +
  labs(fill = "Commercial Shrimp Genus Count"))

(introduced_species_map <- create_map(introduced_species) +
  labs(fill = "Shrimp species count"))

(introduced_genus_map <- create_map(introduced_genus) +
  labs(fill = "Shrimp species count"))

(species_hdi <- left_join(num_all_species_iso3c, hdi, by = "country") %>%
    filter(!is.na(region)) %>%
  ggplot(aes(x = hdi, y = log(num_species), color = region)) +
  geom_point() +
    scale_color_viridis_d(end = 0.9) + 
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Human Development Index", y = "log(Shrimp Species Count", color = "Region") +
    theme_light())

(genus_hdi <- left_join(num_all_genus_iso3c, hdi, by = "country") %>%
    filter(!is.na(region)) %>%
  ggplot(aes(x = hdi, y = log(num_species), color = region)) +
  geom_point() +
    scale_color_viridis_d(end = 0.9) + 
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Human Development Index", y = "log(Shrimp Genus Count", color = "Region") +
    theme_light())

(species_box <- num_all_species_iso3c %>%
  exploreARTIS::add_region("country", region.col.name = "region") %>%
  filter(!is.na(region), region != "Antarctica") %>%
  ggplot(aes(x = region, y = num_species, fill = region)) +
  geom_violin(alpha = 0.5) +
  geom_boxplot(alpha = 0.5) +
  scale_fill_manual(values = artis_palette(7)) +
  theme_light() +
  labs(x = "", y = "Shrimp species count") +
  guides(fill = "none"))

(genus_box <- num_all_genus_iso3c %>%
  exploreARTIS::add_region("country", region.col.name = "region") %>%
  filter(!is.na(region), region != "Antarctica") %>%
  ggplot(aes(x = region, y = num_species, fill = region)) +
  geom_violin(alpha = 0.5) +
  geom_boxplot(alpha = 0.5) +
  scale_fill_manual(values = artis_palette(7)) +
  theme_light() +
  labs(x = "", y = "Shrimp species count") +
  guides(fill = "none"))

num_all_genus_iso3c %>%
  exploreARTIS::add_region("country", region.col.name = "region") %>%
  filter(!is.na(region), region != "Antarctica") %>%
  ggplot(aes(x = region, y = num_species, fill = region)) +
  geom_boxplot() +
  scale_fill_manual(values = artis_palette(7)) +
  theme_light()
```

```{r obtain NOAA data}
bottom_trawl_2015_2024 <- read.csv("data/2015_2024.csv")
bottom_trawl_2014_2005 <- read.csv("data/2014_2005.csv")
bottom_trawl_2004_1995 <- read.csv("data/2004_1995.csv")
bottom_trawl_1994_1982 <- read.csv("data/1994_1982.csv")

# Combine csv's
trawl_data <- bind_rows(bottom_trawl_2015_2024,
          bottom_trawl_2014_2005,
          bottom_trawl_2004_1995,
          bottom_trawl_1994_1982)

# Decapods in Aleutian Islands
trawl_data %>% group_by(Survey.year, Survey.name) %>%
  summarize(weight = sum(Taxon.weight..kg.)) %>%
  ggplot(aes(x = Survey.year, y = weight, color = Survey.name)) +
  geom_line() +
  theme_light() + 
  labs(x = "", y = "Total Decapoda Weight (kg)", color = "Alaskan Bottom Trawl Survey")

```

```{r}
# Obtain country information
countries <- occ_count_country() %>%
  pull(iso2)

# Obtaining gbif abundance information by country
shrimp_gbif <- gbif_abundance(scientific_name = "Decapoda", countries)
ostracoda_gbif <- gbif_abundance(scientific_name = "Ostracoda", countries)

shrimp_gbif_modified <- left_join(shrimp_gbif, occ_count_country() %>% select(iso2, iso3), by = c("country" = "iso2")) %>%
  exploreARTIS::add_region("iso3", region.col.name = "region") %>%
  rename(iso3c = "iso3")

ostracoda_gbif_modified <- left_join(ostracoda_gbif, occ_count_country() %>% select(iso2, iso3), by = c("country" = "iso2")) %>%
  exploreARTIS::add_region("iso3", region.col.name = "region") %>%
  rename(iso3c = "iso3")
  

decapoda_total <- gbif_time_series(shrimp_gbif_modified, taxa_name = "Decapoda", group_by_region = FALSE)
decapoda_country <- gbif_time_series(shrimp_gbif_modified, taxa_name = "Decapoda", group_by_region = TRUE)

pstracoda_total <- gbif_time_series(ostracoda_gbif_modified, taxa_name = "Ostracoda", group_by_region = FALSE)
ostracoda_country <- gbif_time_series(ostracoda_gbif_modified, taxa_name = "Ostracoda", group_by_region = TRUE)


 # %>% filter(date > make_date(1980, 1, 1)) Pipe data through filter if needed

result

shrimp_gbif_modified %>%
  group_by(date) %>%
  drop_na() %>%
  summarize(count = sum(count)) %>%
  ggplot(aes(x = date, y = count)) +
  geom_line()
occ_search(scientificName = "Ostracoda")

# Plot target taxa time series
gbif_time_series(shrimp_gbif, taxa_name = "Decapoda")
gbif_time_series(ostracoda_gbif, taxa_name = "Ostracoda")


result$data  # View the data
occ_search(scientificName = "Macrobrachium", limit = 1321)$data %>%
  group_by(year) %>%
  summarize(count = n()) %>%
  ggplot(aes(x = year, y = count)) +
  geom_line()
  

# Do not include conutries - quicker 
dataa <- data.frame(date = 1920:2024, count = NA)
for (i in 1920:2024) {
  result <- occ_count(scientificName = "Decapoda", year = i)
  dataa$count[which(dataa$date == i)] <- result
}

gbif_time_series(dataa, taxa_name = "Decapda", group_by_region = FALSE)
  
result$data %>%
  mutate(eventDate = str_trunc(eventDate, 4, ellipsis = ""),
         eventDate = make_date(eventDate, 1, 1)) %>%
  group_by(eventDate) %>%
  summarize(total = n()) %>%
  ggplot(aes(x = eventDate, y = total)) +
  geom_line()
str_trunc("paleontologist", 5, "right", ellipsis = "")
```

```{r Save images}
ggsave("images/all_species_count_map.jpg", plot = all_species_count_map, device = "jpeg", width = 6, height = 4)

ggsave("images/all_genus_count_map.jpg", plot = all_genus_count_map, device = "jpeg", width = 6, height = 4)

ggsave("images/commercial_species_count_map.jpg", plot = commercial_species_count_map, device = "jpeg", width = 6, height = 4)

ggsave("images/commercial_genus_count_map.jpg", plot = commercial_genus_count_map, device = "jpeg", width = 6, height = 4)

ggsave("images/introduced_species_map.jpg", plot = introduced_species_map, device = "jpeg", width = 6, height = 4)

ggsave("images/introduced_genus_map.jpg", plot = introduced_genus_map, device = "jpeg", width = 6, height = 4)

ggsave("images/species_hdi.jpg", plot = species_hdi, device = "jpeg", width = 6, height = 4)

ggsave("images/genus_hdi.jpg", plot = genus_hdi, device = "jpeg", width = 6, height = 4)

ggsave("images/species_box.jpg", plot = species_box, device = "jpeg", width = 6, height = 4)

ggsave("images/genus_box.jpg", plot = genus_box, device = "jpeg", width = 6, height = 4)

ggsave("images/decapoda_total.jpg", plot = decapoda_total, device = "jpeg", width = 6, height = 4)

ggsave("images/decapoda_country.jpg", plot = decapoda_country, device = "jpeg", width = 6, height = 4)

ggsave("images/ostracoda_total.jpg", plot = ostracoda_total, device = "jpeg", width = 6, height = 4)

ggsave("images/ostracoda_country.jpg", plot = ostracoda_country, device = "jpeg", width = 6, height = 4)
```
